# Generated by Django 3.2.3 on 2021-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_started',
            field=models.IntegerField(default=0),
        ),
    ]
